#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 35003e98-b706-4f4d-a86f-8f59484a284e
# Source File: ..\..\SAPIEN\PowerShell Studio\Files\Account GUI Blank.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
MggAAB+LCAAAAAAABABllsfK7EgShfcF9Q4/vS1olbwEty/IlKSStyWzk/fe6+m75s5mYGKVkWQG
SZ4TfPHLTON+S6eTDZfw57uYy7775y/4b/Cv3/fbz88vbSrzsgsbrmxSNWzT31Qc92u3/PDO+4du
wq7+e5izX8D/nftzm+un9nenQibo4LZW+RTFaCxD/Tdoim3cFrSRyzeABQuAPFV1KM6vbsZqBTF7
yeWwHRZh5wkokXTRtCecc37KAAzeb016IUjLBk2xx0bRtMpsm2EBLPq0hJPnPRtA0Vd294Fst406
OzjCyhqYnu0AYdl+ZfFv/oyzHBHP834zsyswpDHj1zya37QB4MX1FE2AtQ1NN5FT0/0CpQ6czYwm
Ya8SyDvdgXsdmAQbf2gr9ICDHfaFtteK+63wTuIlDtvhnZknprxeENfOHUpYCnDV5Zc4WrOSOWgP
orkZUhzOPBS5Fw4U9ZABZe3Sn0mNcWSCcer7TYlszxAiHGOpwC0DzHSTvIoxbmikYHYyCj30czoo
n6R8FZS9xRlfk63vE6EoYgBZgfwylBUJotd7ed5vvv3RZIZSULqKjD4TPd61syPMwLoojo8sSvZx
hLhlGVtTBjtZntYaWMjQWe0TJoa02qFifjeVNlOdcL/p1KEp0poENV+fsaDIreiBdWlxSdBTnSJh
2sJR+1N/LGDTlEmwO9t4tEbKJFayf2hWFKKGH1veeo/i/TYFEf9gGkje9kDn6mpKOKkYqWEwUWym
HqEbIvFR4V5A0Fv1juQXMDjaLrTOwLEd2OMkTEaaEqek7HyrEZQ2LBuJ7xi2lpVDJ1remDWBcHY3
CcJM86zecmzeehsjFyvrUUrwnE2jja/TmMGTzZX2reMJ7xz+eL8lQXphp113+gjGxCqCwtkeiTEi
dQmLTmfhVum2TmqbUutaymlvIy1K+Hxwm1r3bPyIp71t80n71PjXb5VhFGQZEZCv2LiK6aOTBHrz
hGJSfxBpsjFSb498Co8F9w4lKDLCkWiUOPfsYjPGl3cEVE8vMN7Q4Ha/9XkamR8KhBuwpPErDNNE
lAOxPSig0B4c/Lzmt0/JcfMOTNGED4PcnuEjhNoxel3xZzF4C+/A+ORsHr3fAoKtaYbGOCo3m4M2
KW4n2j0FwNk7pNaylcejpFaVqc5iWhfX/k9/J9/+LphVdAp1ZBUbnUOnm8OAv9+urXhuA8MLC1lk
O3apEROBqgo31djmdGo2XprKw4C5IDV6lunbWYj5vqP0caZqL/Vtv0rGKby3cDrJVwU5UOjraUul
gYUEwUsNjQszCDh8Iq1yhocaPhyffGxpradbfCbL+TU/IkQSc04sLPoxVzSsImfLOuT9ttCCkm48
YNvMpJVO6MIbLrjAkg+4kiHr4iUKOrqWYbBuboSkpMwFpAGabfji8MG7XMjMJCFJuIFh76tpO04y
hOHYlCUIHk71xLWqMDbLugYXIjTcYG17NDzPfn0O8QG9LviNyjUZ4pI6pw8mQCfXzjsI0/fwfqNG
Luq0s9KM03ZJuxDSHnypMqkZauPidq/K2WuV+aKCqm3tjINckgnUIHfFVu05BAlS9rXHt2uL+O39
NkBxZeuLcNAeBmJ6WdUbWW9pP4Sfx0ZIqBeS9QNiO7Ktoi026AxVXU8l6ta1j7Yqn1DYoQwNePYh
f98GdF6T1FAfE3JactyCgAndIowqqe5kSG2c1BQ9WOL8tfIgpIQvWhn1LKBqcjOkMkHWhqxIcFS0
Wzboq6mOV0vLLlvdZd+/RTuQeDviptVPQoKccOAwUJRrRJtacpE+eZ8S8Nn0ZZ7mTZulykkOBUGW
qJfsWXq/PdsDHIY4SOzej01mPd0P0nz4LgRVa2E6Ozb4vLLYBODe6QSlimP5bcZQpZ3E6XwyoPzJ
Qlw+o6/Hvu5VMp6efAlFNOkgchS6crB2SH1WWEpCrk2wxqzEzoYkOaCeL0glkatD3t2+t1VWCl5y
PoyRQiPp2IToy6wRBI/4kwd2mdbEjm861DXkVBdG8CnbPEzUwmrGHEXDwPgIJ52R7sthZIksZQg+
thFPcYBPL79PhenLLHyz8mGqccFQ+g2E+7RKTG/VLmNexiEyValLPvIjvuRmkMHPYEZ7+OGFtwgQ
fA8QFPvBgcnuoS+K//kF/EH1H2hT85y2UVOm8w/w3fkF/O+M8PtfKumPODIIAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
     Generated on:       5/24/2018 2:47 PM
     Generated by:       dfindley
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Account_GUI_Blank_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAccountCreation = New-Object 'System.Windows.Forms.Form'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonNo = New-Object 'System.Windows.Forms.Button'
	$buttonYes = New-Object 'System.Windows.Forms.Button'
	$labelContinueWithTheseSet = New-Object 'System.Windows.Forms.Label'
	$textbox5 = New-Object 'System.Windows.Forms.TextBox'
	$labelTeamName = New-Object 'System.Windows.Forms.Label'
	$textbox4 = New-Object 'System.Windows.Forms.TextBox'
	$labelJobTitle = New-Object 'System.Windows.Forms.Label'
	$textbox3 = New-Object 'System.Windows.Forms.TextBox'
	$labelUsername = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonCancel = New-Object 'System.Windows.Forms.Button'
	$buttonContinue = New-Object 'System.Windows.Forms.Button'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelEnterLastName = New-Object 'System.Windows.Forms.Label'
	$labelEnterFirstName = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$errorprovider1 = New-Object 'System.Windows.Forms.ErrorProvider'
	$fileToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$exitToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$helpToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formAccountCreation_Load={
		#TODO: Initialize Form Controls here
		Import-Module ActiveDirectory
	}
	
	$groupbox1_Enter={
		#TODO: Place custom script here
		
	}
	
	$buttonContinue_Click={
		#TODO: Place custom script here
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$textbox3.Text = $UserName
		$Account = (dsquery user -samid $UserName)
		
		if ($Account -eq $null)
		{
		$statusbar1.Text = "Username, $UserName, is available for use. "
		}
		else
		{
		$ErrorMessage = "Username, $UserName, is not available. Please manually enter one."
		$errorprovider1.SetIconAlignment($textbox3, 'MiddleRight')
		$errorprovider1.SetError($textbox3,($ErrorMessage))
		$statusbar1.Text = $ErrorMessage	
		}
	}
	
	$textbox3_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$buttonCancel_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonYes_Click={
		#TODO: Place custom script here
		$textbox3.Text = $UserName
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$FullName = "$FirstName " + "$LastName"
		$SamAccountName = $UserName
		$GivenName = $FirstName
		$Surname = $LastName
		$EmailAddress = "$UserName @company.com"
		$StreetAddress = "12345 S. Road"
		$City = "City"
		$State = "State"
		$Company = "Company Name"
		$PhoneNumber = "555-555-5555"
		$AccountName = $UserName
		$AccountPass = "password"
		$EncryptPass = convertto-securestring $AccountPass -asplaintext -force
		$JobTitle = $textbox4.Text
		$TeamName = $textbox5.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$Department = $textbox4.Text
		
		New-ADUser -Name $FullName `
				   -SamAccountName $SamAccountName `
				   -GivenName $GivenName
		
		Get-ADUser $UserName | Set-ADUser -GivenName $FirstName `
										  -Surname $LastName `
										  -EmailAddress $EmailAddress `
										  -Company $Company `
										  -UserPrincipalName "$UserName@companydomain.com" `
										  -Enable $true `
										  -DisplayName "$FirstName $LastName" `
										  -ChangePasswordAtLogon:$false `
										  -Title $JobTitle `
										  -MobilePhone $PhoneNumber `
										  -PasswordNeverExpires $true
	}
	
	$textbox5_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$exitToolStripMenuItem_Click={
		#TODO: Place custom script here
		$formAccountCreation.Close()
		
	}
	
	$aboutToolStripMenuItem_Click={
		#TODO: Place custom script here
		#------------------------------------------------------------------------
		# Source File Information (DO NOT MODIFY)
		# Source ID: 9a2aa374-bb49-4c52-a506-4dacee24e610
		# Source File: C:\Users\dfindley\Documents\SAPIEN\PowerShell Studio\Files\About Blank.psf
		#------------------------------------------------------------------------
		
	<#
	    .NOTES
	    --------------------------------------------------------------------------------
	     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
	     Generated on:       5/24/2018 2:03 PM
	     Generated by:       dfindley
	    --------------------------------------------------------------------------------
	    .DESCRIPTION
	        GUI script generated by PowerShell Studio 2018
	#>
		
		
		#----------------------------------------------
		#region Application Functions
		#----------------------------------------------
		
		#endregion Application Functions
		
		#----------------------------------------------
		# Generated Form Function
		#----------------------------------------------
		function Show-About_Blank_psf
		{
			
			#----------------------------------------------
			#region Import the Assemblies
			#----------------------------------------------
			[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
			[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
			#endregion Import Assemblies
			
			#----------------------------------------------
			#region Generated Form Objects
			#----------------------------------------------
			[System.Windows.Forms.Application]::EnableVisualStyles()
			$formAbout = New-Object 'System.Windows.Forms.Form'
			$labelVersion10 = New-Object 'System.Windows.Forms.Label'
			$labelADAccountCreationToo = New-Object 'System.Windows.Forms.Label'
			$buttonOK = New-Object 'System.Windows.Forms.Button'
			$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
			#endregion Generated Form Objects
			
			#----------------------------------------------
			# User Generated Script
			#----------------------------------------------
			
			$formAbout_Load = {
				#TODO: Initialize Form Controls here
				
			}
			
			$labelADAccountCreationToo_Click = {
				#TODO: Place custom script here
				
			}
			
			# --End User Generated Script--
			#----------------------------------------------
			#region Generated Events
			#----------------------------------------------
			
			$Form_StateCorrection_Load =
			{
				#Correct the initial state of the form to prevent the .Net maximized form issue
				$formAbout.WindowState = $InitialFormWindowState
			}
			
			$Form_Cleanup_FormClosed =
			{
				#Remove all event handlers from the controls
				try
				{
					$labelADAccountCreationToo.remove_Click($labelADAccountCreationToo_Click)
					$formAbout.remove_Load($formAbout_Load)
					$formAbout.remove_Load($Form_StateCorrection_Load)
					$formAbout.remove_FormClosed($Form_Cleanup_FormClosed)
				}
				catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
			}
			#endregion Generated Events
			
			#----------------------------------------------
			#region Generated Form Code
			#----------------------------------------------
			$formAbout.SuspendLayout()
			#
			# formAbout
			#
			$formAbout.Controls.Add($labelVersion10)
			$formAbout.Controls.Add($labelADAccountCreationToo)
			$formAbout.Controls.Add($buttonOK)
			$formAbout.AcceptButton = $buttonOK
			$formAbout.AutoScaleDimensions = '6, 13'
			$formAbout.AutoScaleMode = 'Font'
			$formAbout.BackColor = 'WhiteSmoke'
			$formAbout.ClientSize = '284, 262'
			$formAbout.FormBorderStyle = 'FixedDialog'
			$formAbout.MaximizeBox = $False
			$formAbout.MinimizeBox = $False
			$formAbout.Name = 'formAbout'
			$formAbout.StartPosition = 'CenterScreen'
			$formAbout.Text = 'About'
			$formAbout.add_Load($formAbout_Load)
			#
			# labelVersion10
			#
			$labelVersion10.AutoSize = $True
			$labelVersion10.Location = '99, 97'
			$labelVersion10.Name = 'labelVersion10'
			$labelVersion10.Size = '64, 17'
			$labelVersion10.TabIndex = 2
			$labelVersion10.Text = 'Version 1.0 '
			$labelVersion10.UseCompatibleTextRendering = $True
			#
			# labelADAccountCreationToo
			#
			$labelADAccountCreationToo.AutoSize = $True
			$labelADAccountCreationToo.Location = '71, 80'
			$labelADAccountCreationToo.Name = 'labelADAccountCreationToo'
			$labelADAccountCreationToo.Size = '135, 17'
			$labelADAccountCreationToo.TabIndex = 1
			$labelADAccountCreationToo.Text = 'AD Account Creation Tool'
			$labelADAccountCreationToo.UseCompatibleTextRendering = $True
			$labelADAccountCreationToo.add_Click($labelADAccountCreationToo_Click)
			#
			# buttonOK
			#
			$buttonOK.Anchor = 'Bottom, Right'
			$buttonOK.DialogResult = 'OK'
			$buttonOK.Location = '197, 227'
			$buttonOK.Name = 'buttonOK'
			$buttonOK.Size = '75, 23'
			$buttonOK.TabIndex = 0
			$buttonOK.Text = '&OK'
			$buttonOK.UseCompatibleTextRendering = $True
			$buttonOK.UseVisualStyleBackColor = $True
			$formAbout.ResumeLayout()
			#endregion Generated Form Code
			
			#----------------------------------------------
			
			#Save the initial state of the form
			$InitialFormWindowState = $formAbout.WindowState
			#Init the OnLoad event to correct the initial state of the form
			$formAbout.add_Load($Form_StateCorrection_Load)
			#Clean up the control events
			$formAbout.add_FormClosed($Form_Cleanup_FormClosed)
			#Show the Form
			return $formAbout.ShowDialog()
			
		} #End Function
		
		#Call the form
		Show-About_Blank_psf | Out-Null
		
	
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAccountCreation.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonYes.remove_Click($buttonYes_Click)
			$textbox5.remove_TextChanged($textbox5_TextChanged)
			$textbox3.remove_TextChanged($textbox3_TextChanged)
			$buttonCancel.remove_Click($buttonCancel_Click)
			$buttonContinue.remove_Click($buttonContinue_Click)
			$groupbox1.remove_Enter($groupbox1_Enter)
			$formAccountCreation.remove_Load($formAccountCreation_Load)
			$exitToolStripMenuItem.remove_Click($exitToolStripMenuItem_Click)
			$aboutToolStripMenuItem.remove_Click($aboutToolStripMenuItem_Click)
			$formAccountCreation.remove_Load($Form_StateCorrection_Load)
			$formAccountCreation.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formAccountCreation.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	$menustrip1.SuspendLayout()
	#
	# formAccountCreation
	#
	$formAccountCreation.Controls.Add($statusbar1)
	$formAccountCreation.Controls.Add($groupbox2)
	$formAccountCreation.Controls.Add($groupbox1)
	$formAccountCreation.Controls.Add($menustrip1)
	$formAccountCreation.AutoScaleDimensions = '6, 13'
	$formAccountCreation.AutoScaleMode = 'Font'
	$formAccountCreation.ClientSize = '868, 511'
	$formAccountCreation.MainMenuStrip = $menustrip1
	$formAccountCreation.Name = 'formAccountCreation'
	$formAccountCreation.Text = 'Account Creation'
	$formAccountCreation.add_Load($formAccountCreation_Load)
	#
	# statusbar1
	#
	$statusbar1.Font = 'Segoe UI, 9.75pt'
	$statusbar1.Location = '0, 489'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '868, 22'
	$statusbar1.TabIndex = 2
	$statusbar1.Text = 'Account Creation Tool v1.0'
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonNo)
	$groupbox2.Controls.Add($buttonYes)
	$groupbox2.Controls.Add($labelContinueWithTheseSet)
	$groupbox2.Controls.Add($textbox5)
	$groupbox2.Controls.Add($labelTeamName)
	$groupbox2.Controls.Add($textbox4)
	$groupbox2.Controls.Add($labelJobTitle)
	$groupbox2.Controls.Add($textbox3)
	$groupbox2.Controls.Add($labelUsername)
	$groupbox2.Font = 'Segoe UI, 9.75pt'
	$groupbox2.Location = '38, 187'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '695, 187'
	$groupbox2.TabIndex = 1
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Account Details:'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# buttonNo
	#
	$buttonNo.Location = '528, 154'
	$buttonNo.Name = 'buttonNo'
	$buttonNo.Size = '75, 23'
	$buttonNo.TabIndex = 8
	$buttonNo.Text = 'No'
	$buttonNo.UseCompatibleTextRendering = $True
	$buttonNo.UseVisualStyleBackColor = $True
	#
	# buttonYes
	#
	$buttonYes.Location = '612, 154'
	$buttonYes.Name = 'buttonYes'
	$buttonYes.Size = '75, 23'
	$buttonYes.TabIndex = 7
	$buttonYes.Text = 'Yes'
	$buttonYes.UseCompatibleTextRendering = $True
	$buttonYes.UseVisualStyleBackColor = $True
	$buttonYes.add_Click($buttonYes_Click)
	#
	# labelContinueWithTheseSet
	#
	$labelContinueWithTheseSet.AutoSize = $True
	$labelContinueWithTheseSet.Location = '20, 154'
	$labelContinueWithTheseSet.Name = 'labelContinueWithTheseSet'
	$labelContinueWithTheseSet.Size = '178, 22'
	$labelContinueWithTheseSet.TabIndex = 6
	$labelContinueWithTheseSet.Text = 'Continue with these settings?'
	$labelContinueWithTheseSet.UseCompatibleTextRendering = $True
	#
	# textbox5
	#
	$textbox5.Location = '145, 104'
	$textbox5.Name = 'textbox5'
	$textbox5.Size = '186, 25'
	$textbox5.TabIndex = 5
	$textbox5.add_TextChanged($textbox5_TextChanged)
	#
	# labelTeamName
	#
	$labelTeamName.AutoSize = $True
	$labelTeamName.Location = '20, 103'
	$labelTeamName.Name = 'labelTeamName'
	$labelTeamName.Size = '79, 22'
	$labelTeamName.TabIndex = 4
	$labelTeamName.Text = 'Team Name:'
	$labelTeamName.UseCompatibleTextRendering = $True
	#
	# textbox4
	#
	$textbox4.Location = '145, 63'
	$textbox4.Name = 'textbox4'
	$textbox4.Size = '186, 25'
	$textbox4.TabIndex = 3
	#
	# labelJobTitle
	#
	$labelJobTitle.AutoSize = $True
	$labelJobTitle.Location = '20, 62'
	$labelJobTitle.Name = 'labelJobTitle'
	$labelJobTitle.Size = '57, 22'
	$labelJobTitle.TabIndex = 2
	$labelJobTitle.Text = 'Job Title:'
	$labelJobTitle.UseCompatibleTextRendering = $True
	#
	# textbox3
	#
	$textbox3.Location = '145, 22'
	$textbox3.Name = 'textbox3'
	$textbox3.Size = '186, 25'
	$textbox3.TabIndex = 1
	$textbox3.add_TextChanged($textbox3_TextChanged)
	#
	# labelUsername
	#
	$labelUsername.AutoSize = $True
	$labelUsername.Location = '20, 25'
	$labelUsername.Name = 'labelUsername'
	$labelUsername.Size = '67, 22'
	$labelUsername.TabIndex = 0
	$labelUsername.Text = 'Username:'
	$labelUsername.UseCompatibleTextRendering = $True
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonCancel)
	$groupbox1.Controls.Add($buttonContinue)
	$groupbox1.Controls.Add($textbox2)
	$groupbox1.Controls.Add($labelEnterLastName)
	$groupbox1.Controls.Add($labelEnterFirstName)
	$groupbox1.Controls.Add($textbox1)
	$groupbox1.Font = 'Segoe UI, 9.75pt'
	$groupbox1.Location = '38, 44'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '695, 125'
	$groupbox1.TabIndex = 0
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Enter Name:'
	$groupbox1.UseCompatibleTextRendering = $True
	$groupbox1.add_Enter($groupbox1_Enter)
	#
	# buttonCancel
	#
	$buttonCancel.DialogResult = 'Cancel'
	$buttonCancel.Location = '528, 96'
	$buttonCancel.Name = 'buttonCancel'
	$buttonCancel.Size = '75, 23'
	$buttonCancel.TabIndex = 5
	$buttonCancel.Text = 'Cancel'
	$buttonCancel.UseCompatibleTextRendering = $True
	$buttonCancel.UseVisualStyleBackColor = $True
	$buttonCancel.add_Click($buttonCancel_Click)
	#
	# buttonContinue
	#
	$buttonContinue.Location = '612, 96'
	$buttonContinue.Name = 'buttonContinue'
	$buttonContinue.Size = '75, 23'
	$buttonContinue.TabIndex = 4
	$buttonContinue.Text = 'Continue'
	$buttonContinue.UseCompatibleTextRendering = $True
	$buttonContinue.UseVisualStyleBackColor = $True
	$buttonContinue.add_Click($buttonContinue_Click)
	#
	# textbox2
	#
	$textbox2.Location = '145, 73'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '186, 25'
	$textbox2.TabIndex = 3
	#
	# labelEnterLastName
	#
	$labelEnterLastName.AutoSize = $True
	$labelEnterLastName.Location = '20, 76'
	$labelEnterLastName.Name = 'labelEnterLastName'
	$labelEnterLastName.Size = '104, 22'
	$labelEnterLastName.TabIndex = 2
	$labelEnterLastName.Text = 'Enter Last Name:'
	$labelEnterLastName.UseCompatibleTextRendering = $True
	#
	# labelEnterFirstName
	#
	$labelEnterFirstName.AutoSize = $True
	$labelEnterFirstName.Location = '20, 34'
	$labelEnterFirstName.Name = 'labelEnterFirstName'
	$labelEnterFirstName.Size = '106, 22'
	$labelEnterFirstName.TabIndex = 1
	$labelEnterFirstName.Text = 'Enter First Name:'
	$labelEnterFirstName.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '145, 31'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '186, 25'
	$textbox1.TabIndex = 0
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($fileToolStripMenuItem)
	[void]$menustrip1.Items.Add($helpToolStripMenuItem)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '868, 24'
	$menustrip1.TabIndex = 3
	$menustrip1.Text = 'menustrip1'
	#
	# errorprovider1
	#
	$errorprovider1.ContainerControl = $formAccountCreation
	#
	# fileToolStripMenuItem
	#
	[void]$fileToolStripMenuItem.DropDownItems.Add($exitToolStripMenuItem)
	$fileToolStripMenuItem.Name = 'fileToolStripMenuItem'
	$fileToolStripMenuItem.Size = '37, 20'
	$fileToolStripMenuItem.Text = 'File'
	#
	# exitToolStripMenuItem
	#
	$exitToolStripMenuItem.Name = 'exitToolStripMenuItem'
	$exitToolStripMenuItem.Size = '92, 22'
	$exitToolStripMenuItem.Text = 'Exit'
	$exitToolStripMenuItem.add_Click($exitToolStripMenuItem_Click)
	#
	# helpToolStripMenuItem
	#
	[void]$helpToolStripMenuItem.DropDownItems.Add($aboutToolStripMenuItem)
	$helpToolStripMenuItem.Name = 'helpToolStripMenuItem'
	$helpToolStripMenuItem.Size = '44, 20'
	$helpToolStripMenuItem.Text = 'Help'
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = 'aboutToolStripMenuItem'
	$aboutToolStripMenuItem.Size = '107, 22'
	$aboutToolStripMenuItem.Text = 'About'
	$aboutToolStripMenuItem.add_Click($aboutToolStripMenuItem_Click)
	$menustrip1.ResumeLayout()
	$groupbox1.ResumeLayout()
	$groupbox2.ResumeLayout()
	$formAccountCreation.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAccountCreation.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAccountCreation.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAccountCreation.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formAccountCreation.ShowDialog()

} #End Function

#Call the form
Show-Account_GUI_Blank_psf | Out-Null
