#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 35003e98-b706-4f4d-a86f-8f59484a284e
# Source File: ..\..\SAPIEN\PowerShell Studio\Files\Account GUI Blank.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
5gYAAB+LCAAAAAAABABllUevqwYQhfdI/IerbJFCMVW6eRIdA6aYzo5eDJhu4Nfn5mUTKbMajWZW
Z875vp9F9t6L+RSSNfn6aZbmPfz1x+1P9I9fIPD19W3OTdUMSSc1XWEkffGLzbL3Nqxfsnf/4rpk
eP05LuU3/L+939fSe+5/9XTroEuHxM6bZXlT4Nl/i2OFru/RHW8r+2CgMjdg7uxXkbdpdZBGM2Cm
gpmT23rOy7wRPhE9437a1FdhIiBAuBSDha935PV3JZ686aXyonDGFkGWB2RyCAXlJa10n7INw4Ml
25yu9o7ielfKueMMqAIqLLKw7HLTQGDpQ/omqoRChbaB8dwTxq5yXlrlRBDefllyfBGiosmOvTL8
89ZsMVNZiXXDVZpY34hCLez5pBAov0ctCLBwh2vuBYtWSeH6G2GsXmSLtBmr+KSuzxnTutZLfPlA
3vz9uK+xwtQ5Gzzmw7qEUx68I3M3iw9wcVVBIJpa3+7TneHtPOhTUiIw4ZHizvAaV3WxhQGBGBh3
OYSbMOTBIg6OQA2Wt4NlSM6JDvTDMbJAk5oF2UBAwZ3pMJMEH/ptRXfiLDrVECJUv+fV2YpWdbMe
SZPVjfAhenWgWKPJVe6FR9cpcXaIMMFDb/MZi3QvBYGzuwkJNMv7HZPInfiMMuvUN631H+KLRbbb
dHFQPWIWXJ9FqysOeW9sOTOugnsetgtdVZ944v6s1najQABVLxHx8wG3GfnDeESZvPM68hHC4Id0
e7wY0YkuTV7bh3Z5vefMhsSimSdzz9A+zGocz+15uqxqq30OAp1a6bhRtZ+A1uqOFnpD6JzXGduI
UBB2IrpmSvB41/TmRg0adb0Ua0JpMhCpgXCtol0j6Gn7Of/Y2gEEfsRqXEkbnCY6VCplR32jGug2
xFqFWdVEv8e39slI5nSznRfkmG4DLoOuwj2beuaakMoPpLQumkUkFAQq/ryCD1Lhqb9Vu356tcRN
g1pwiVyejfrc0uHWh/84h/hxjuVv+i4Lo5AsjuU0tPugEQundpnCnogIAg822BpM8phXTGsizNTr
sT2PMrNXJLmrK+aVMtJiT72Cnt5deXt8LYdiJ7KhdKScDodHWPmY6eQ92bIgsFlse44jxzjPgemD
HGGkWg2DqaJjW7ESMqmj1GBnOYZNaTBbVSmj8GHQ941GszIwx+gT43KGnjjUNyDwpiIpzlVp6vxh
Plb/5Lgp5WNF10TV8SWCK1XKsUuGZUxujAyenC0sVdmBXOqQJmCvD4fsTiN7jKwrCLwCP6ApI2g9
LhnsWQ9CiV7VU9I4Zy4WeN7Csiq66IHkMem/Fq4mr2GXE/WzUUVBm9RG8y6UQMd2LjIIqMTD/AkO
Esv47cWimExQEuYIPirZW8GaKwolKa3rKLbAKVXmt3D1KVpRBiPOIys6iskySDI0qtoNOxBwUD50
w/650idy86Iw3/XsVYaxuta3qmj61V4skZrwyhNw6V1SJEcmp4P+vA7lFVUbSyMmLx+TzO/jj7Oi
9Uo9KUfyO0YG1q4zxZTEbj5q9S3SNJyPCo1IqwMVVi7p37h1iC5zkkqUaV1Jd8aUJN3uXw05Ef4C
AhR0vZUeo9CrrWZGM5Zb4JwJUQwRh0FtUOI/Weh4b2pf4gxBuLwoTr8xxxE+JkT3K11LFt6rwrUS
0DsIPPPJbMlezvHTETFhbFfJ7eFmVTzLIFQ2v8MZvUI5su9Yb4lN2EpibwkHXr2FxP6EDnbOR1yn
jOPff1QQbgu08I7WBxYtlB9WDNjwNclESWd0EZPRnAy6K97IR93CAhyXnyTutIplv+HfePkNGnZZ
ij7tmmL5gn8m3/B/ufbrb2rXQHzmBgAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
     Generated on:       5/24/2018 10:40 AM
     Generated by:       dfindley
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Account_GUI_Blank_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAccountCreation = New-Object 'System.Windows.Forms.Form'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonNo = New-Object 'System.Windows.Forms.Button'
	$buttonYes = New-Object 'System.Windows.Forms.Button'
	$labelContinueWithTheseSet = New-Object 'System.Windows.Forms.Label'
	$textbox5 = New-Object 'System.Windows.Forms.TextBox'
	$labelTeamName = New-Object 'System.Windows.Forms.Label'
	$textbox4 = New-Object 'System.Windows.Forms.TextBox'
	$labelJobTitile = New-Object 'System.Windows.Forms.Label'
	$textbox3 = New-Object 'System.Windows.Forms.TextBox'
	$labelUsername = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonCancel = New-Object 'System.Windows.Forms.Button'
	$buttonContinue = New-Object 'System.Windows.Forms.Button'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelEnterLastName = New-Object 'System.Windows.Forms.Label'
	$labelEnterFirstName = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$errorprovider1 = New-Object 'System.Windows.Forms.ErrorProvider'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formAccountCreation_Load={
		#TODO: Initialize Form Controls here
		Import-Module ActiveDirectory
	}
	
	$groupbox1_Enter={
		#TODO: Place custom script here
		
	}
	
	$buttonContinue_Click={
		#TODO: Place custom script here
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$textbox3.Text = $UserName
		$Account = (dsquery user -samid $UserName)
		
		if ($Account -eq $null)
		{
		$statusbar1.Text = "Username, $UserName, is available for use. "
		}
		else
		{
		$ErrorMessage = "Username, $UserName, is not available. Please manually enter one."
		$errorprovider1.SetIconAlignment($textbox3, 'MiddleRight')
		$errorprovider1.SetError($textbox3,($ErrorMessage))
		$statusbar1.Text = $ErrorMessage	
		}
	}
	
	$textbox3_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$buttonCancel_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonYes_Click={
		#TODO: Place custom script here
		$textbox3.Text = $UserName
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$FullName = "$FirstName " + "$LastName"
		$SamAccountName = $UserName
		$GivenName = $FirstName
		$Surname = $LastName
		$EmailAddress = "$UserName @company.com"
		$StreetAddress = "12345 S. Road"
		$City = "City"
		$State = "State"
		$Company = "Company Name"
		$PhoneNumber = "555-555-5555"
		$AccountName = $UserName
		$AccountPass = "password"
		$EncryptPass = convertto-securestring $AccountPass -asplaintext -force
		$JobTitle = $textbox4.Text
		$TeamName = $textbox5.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$Department = $textbox4.Text
		
		New-ADUser -Name $FullName `
				   -SamAccountName $SamAccountName `
				   -GivenName $GivenName
		
		Get-ADUser $UserName | Set-ADUser -GivenName $FirstName `
										  -Surname $LastName `
										  -EmailAddress $EmailAddress `
										  -Company $Company `
										  -UserPrincipalName "$UserName@companydomain.com" `
										  -Enable $true `
										  -DisplayName "$FirstName $LastName" `
										  -ChangePasswordAtLogon:$false `
										  -Title $JobTitle `
										  -MobilePhone $PhoneNumber `
										  -PasswordNeverExpires $true
	}
	
	$textbox5_TextChanged={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAccountCreation.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonYes.remove_Click($buttonYes_Click)
			$textbox5.remove_TextChanged($textbox5_TextChanged)
			$textbox3.remove_TextChanged($textbox3_TextChanged)
			$buttonCancel.remove_Click($buttonCancel_Click)
			$buttonContinue.remove_Click($buttonContinue_Click)
			$groupbox1.remove_Enter($groupbox1_Enter)
			$formAccountCreation.remove_Load($formAccountCreation_Load)
			$formAccountCreation.remove_Load($Form_StateCorrection_Load)
			$formAccountCreation.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formAccountCreation.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# formAccountCreation
	#
	$formAccountCreation.Controls.Add($statusbar1)
	$formAccountCreation.Controls.Add($groupbox2)
	$formAccountCreation.Controls.Add($groupbox1)
	$formAccountCreation.AutoScaleDimensions = '6, 13'
	$formAccountCreation.AutoScaleMode = 'Font'
	$formAccountCreation.ClientSize = '868, 511'
	$formAccountCreation.Name = 'formAccountCreation'
	$formAccountCreation.Text = 'Account Creation'
	$formAccountCreation.add_Load($formAccountCreation_Load)
	#
	# statusbar1
	#
	$statusbar1.Font = 'Segoe UI, 9.75pt'
	$statusbar1.Location = '0, 489'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '868, 22'
	$statusbar1.TabIndex = 2
	$statusbar1.Text = 'Account Creation Tool v1.0'
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonNo)
	$groupbox2.Controls.Add($buttonYes)
	$groupbox2.Controls.Add($labelContinueWithTheseSet)
	$groupbox2.Controls.Add($textbox5)
	$groupbox2.Controls.Add($labelTeamName)
	$groupbox2.Controls.Add($textbox4)
	$groupbox2.Controls.Add($labelJobTitile)
	$groupbox2.Controls.Add($textbox3)
	$groupbox2.Controls.Add($labelUsername)
	$groupbox2.Font = 'Segoe UI, 9.75pt'
	$groupbox2.Location = '38, 187'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '695, 187'
	$groupbox2.TabIndex = 1
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Account Details:'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# buttonNo
	#
	$buttonNo.Location = '528, 154'
	$buttonNo.Name = 'buttonNo'
	$buttonNo.Size = '75, 23'
	$buttonNo.TabIndex = 8
	$buttonNo.Text = 'No'
	$buttonNo.UseCompatibleTextRendering = $True
	$buttonNo.UseVisualStyleBackColor = $True
	#
	# buttonYes
	#
	$buttonYes.Location = '612, 154'
	$buttonYes.Name = 'buttonYes'
	$buttonYes.Size = '75, 23'
	$buttonYes.TabIndex = 7
	$buttonYes.Text = 'Yes'
	$buttonYes.UseCompatibleTextRendering = $True
	$buttonYes.UseVisualStyleBackColor = $True
	$buttonYes.add_Click($buttonYes_Click)
	#
	# labelContinueWithTheseSet
	#
	$labelContinueWithTheseSet.AutoSize = $True
	$labelContinueWithTheseSet.Location = '20, 154'
	$labelContinueWithTheseSet.Name = 'labelContinueWithTheseSet'
	$labelContinueWithTheseSet.Size = '178, 22'
	$labelContinueWithTheseSet.TabIndex = 6
	$labelContinueWithTheseSet.Text = 'Continue with these settings?'
	$labelContinueWithTheseSet.UseCompatibleTextRendering = $True
	#
	# textbox5
	#
	$textbox5.Location = '145, 104'
	$textbox5.Name = 'textbox5'
	$textbox5.Size = '186, 25'
	$textbox5.TabIndex = 5
	$textbox5.add_TextChanged($textbox5_TextChanged)
	#
	# labelTeamName
	#
	$labelTeamName.AutoSize = $True
	$labelTeamName.Location = '20, 103'
	$labelTeamName.Name = 'labelTeamName'
	$labelTeamName.Size = '79, 22'
	$labelTeamName.TabIndex = 4
	$labelTeamName.Text = 'Team Name:'
	$labelTeamName.UseCompatibleTextRendering = $True
	#
	# textbox4
	#
	$textbox4.Location = '145, 63'
	$textbox4.Name = 'textbox4'
	$textbox4.Size = '186, 25'
	$textbox4.TabIndex = 3
	#
	# labelJobTitile
	#
	$labelJobTitile.AutoSize = $True
	$labelJobTitile.Location = '20, 62'
	$labelJobTitile.Name = 'labelJobTitile'
	$labelJobTitile.Size = '60, 22'
	$labelJobTitile.TabIndex = 2
	$labelJobTitile.Text = 'Job Titile:'
	$labelJobTitile.UseCompatibleTextRendering = $True
	#
	# textbox3
	#
	$textbox3.Location = '145, 22'
	$textbox3.Name = 'textbox3'
	$textbox3.Size = '186, 25'
	$textbox3.TabIndex = 1
	$textbox3.add_TextChanged($textbox3_TextChanged)
	#
	# labelUsername
	#
	$labelUsername.AutoSize = $True
	$labelUsername.Location = '20, 25'
	$labelUsername.Name = 'labelUsername'
	$labelUsername.Size = '67, 22'
	$labelUsername.TabIndex = 0
	$labelUsername.Text = 'Username:'
	$labelUsername.UseCompatibleTextRendering = $True
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonCancel)
	$groupbox1.Controls.Add($buttonContinue)
	$groupbox1.Controls.Add($textbox2)
	$groupbox1.Controls.Add($labelEnterLastName)
	$groupbox1.Controls.Add($labelEnterFirstName)
	$groupbox1.Controls.Add($textbox1)
	$groupbox1.Font = 'Segoe UI, 9.75pt'
	$groupbox1.Location = '38, 44'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '695, 125'
	$groupbox1.TabIndex = 0
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Enter Name:'
	$groupbox1.UseCompatibleTextRendering = $True
	$groupbox1.add_Enter($groupbox1_Enter)
	#
	# buttonCancel
	#
	$buttonCancel.DialogResult = 'Cancel'
	$buttonCancel.Location = '528, 96'
	$buttonCancel.Name = 'buttonCancel'
	$buttonCancel.Size = '75, 23'
	$buttonCancel.TabIndex = 5
	$buttonCancel.Text = 'Cancel'
	$buttonCancel.UseCompatibleTextRendering = $True
	$buttonCancel.UseVisualStyleBackColor = $True
	$buttonCancel.add_Click($buttonCancel_Click)
	#
	# buttonContinue
	#
	$buttonContinue.Location = '612, 96'
	$buttonContinue.Name = 'buttonContinue'
	$buttonContinue.Size = '75, 23'
	$buttonContinue.TabIndex = 4
	$buttonContinue.Text = 'Continue'
	$buttonContinue.UseCompatibleTextRendering = $True
	$buttonContinue.UseVisualStyleBackColor = $True
	$buttonContinue.add_Click($buttonContinue_Click)
	#
	# textbox2
	#
	$textbox2.Location = '145, 73'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '186, 25'
	$textbox2.TabIndex = 3
	#
	# labelEnterLastName
	#
	$labelEnterLastName.AutoSize = $True
	$labelEnterLastName.Location = '20, 76'
	$labelEnterLastName.Name = 'labelEnterLastName'
	$labelEnterLastName.Size = '104, 22'
	$labelEnterLastName.TabIndex = 2
	$labelEnterLastName.Text = 'Enter Last Name:'
	$labelEnterLastName.UseCompatibleTextRendering = $True
	#
	# labelEnterFirstName
	#
	$labelEnterFirstName.AutoSize = $True
	$labelEnterFirstName.Location = '20, 34'
	$labelEnterFirstName.Name = 'labelEnterFirstName'
	$labelEnterFirstName.Size = '106, 22'
	$labelEnterFirstName.TabIndex = 1
	$labelEnterFirstName.Text = 'Enter First Name:'
	$labelEnterFirstName.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '145, 31'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '186, 25'
	$textbox1.TabIndex = 0
	#
	# errorprovider1
	#
	$errorprovider1.ContainerControl = $formAccountCreation
	$groupbox1.ResumeLayout()
	$groupbox2.ResumeLayout()
	$formAccountCreation.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAccountCreation.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAccountCreation.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAccountCreation.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formAccountCreation.ShowDialog()

} #End Function

#Call the form
Show-Account_GUI_Blank_psf | Out-Null
